server:
  port: 7002

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongo
      password: mongo
      database: recommendation-db

logging:
  level:
    root: INFO
    jp.vmware.sol: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb_recommendation

server:
  port: 8080
