version: '2.1'

services:
  product:
    image: ms-demo-04-persistence-product-service:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb_product

  recommendation:
    image: ms-demo-04-persistence-recommendation-service:latest
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb_recommendation

  review:
    image: ms-demo-04-persistence-review-service:latest
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  product-composite:
    image: ms-demo-04-persistence-product-composite-service:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  workstation:
    image: openjdk:latest
    tty: true

  # $ mongo
  mongodb_product:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: product-db
      TZ: Asia/Tokyo
    ports:
      - "27017:27017"
    #command: mongod --smallfiles
    volumes:
      - ./initdb-mongo-product.d:/docker-entrypoint-initdb.d

  # $ mongo
  mongodb_recommendation:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: recommendation-db
      TZ: Asia/Tokyo
    ports:
      - "27018:27017"
    #command: mongod --smallfiles
    volumes:
      - ./initdb-mongo-recommendation.d:/docker-entrypoint-initdb.d

  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    #image: mysql/mysql-server:5.7.23
    image: mysql/mysql-server
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=vmware
      - MYSQL_PASSWORD=password
    volumes:
      - ./initdb-mysql-review.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uvmware", "-ppassword", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
