server:
  port: 7001

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongo
      password: mongo
      database: product-db

logging:
  level:
    root: INFO
    jp.vmware.sol.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb_product

server:
  port: 8080


